//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAudLect
    {
        public int AudId { get; set; }
        public int LectId { get; set; }
        public int GroupId { get; set; }
        public int Id { get; set; }
        public Nullable<int> TeachSubj_TeacherId { get; set; }
        public Nullable<int> TeachSubj_SubjId { get; set; }
    
        public virtual tbAudience tbAudience { get; set; }
        public virtual tbGroup tbGroup { get; set; }
        public virtual tbLection tbLection { get; set; }
        public virtual tbTeachSubj tbTeachSubj { get; set; }
    }
}
